version: '3.8'
services:
  lotyshop-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=libraryBD
    ports:
      - '5555:5432'